### ISSUE TITLE
Memory leak when using a baseline and multiple counters.

### ISSUE THREAD

**Issue by jeberger** [okuvshynov/b63#18]
In [`run.h:131`](https://github.com/okuvshynov/b63/blob/master/include/b63/run.h#L131),  the `baseline_results` pointer is reallocated once for each counter, but it is only freed once in all at [`run.h:145`](https://github.com/okuvshynov/b63/blob/master/include/b63/run.h#L145), meaning only the last one is freed and the others are leaked.

**Comment by okuvshynov** [comment]
Thanks for reporting!

#19 should allocate baseline results just once
